### ISSUE TITLE
'NoneType' object has no attribute 'split' 

### ISSUE THREAD

**Issue by YJawata** [singer-io/tap-gitlab#20]
Hi, I am currently using Stitchdata for Gitlab integration. After a few days of running smoothly, I suddenly got this error message: 'NoneType' object has no attribute 'split'. And the pipeline has not been working ever since. We haven't really made any changes on Git so I am not sure what caused the issue. Could anyone please advice? Thanks

`2020-10-05 18:58:09,929Z    tap - CRITICAL 'NoneType' object has no attribute 'split'
2020-10-05 18:58:09,929Z    tap - Traceback (most recent call last):
2020-10-05 18:58:09,929Z    tap -   File "tap-env/bin/tap-gitlab", line 33, in <module>
2020-10-05 18:58:09,930Z    tap -     sys.exit(load_entry_point('tap-gitlab==0.5.1', 'console_scripts', 'tap-gitlab')())
2020-10-05 18:58:09,930Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_gitlab/__init__.py", line 292, in main
2020-10-05 18:58:09,930Z    tap -     raise exc
2020-10-05 18:58:09,930Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_gitlab/__init__.py", line 289, in main
2020-10-05 18:58:09,930Z    tap -     main_impl()
2020-10-05 18:58:09,930Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_gitlab/__init__.py", line 284, in main_impl
2020-10-05 18:58:09,930Z    tap -     do_sync()
2020-10-05 18:58:09,930Z    tap -   File "/code/orchestrator/tap-env/lib/python3.5/site-packages/tap_gitlab/__init__.py", line 258, in do_sync
2020-10-05 18:58:09,930Z    tap -     gids = list(filter(None, CONFIG['groups'].split(' ')))
2020-10-05 18:58:09,930Z    tap - AttributeError: 'NoneType' object has no attribute 'split'
2020-10-05 18:58:10,153Z target - INFO Using batch_size_prefernces of {'user_batch_size_preference': None, 'batch_size_preference': None, 'full_table_streams': []}
2020-10-05 18:58:10,154Z target - INFO Requests complete, stopping loop
2020-10-05 18:58:10,207Z   main - INFO Target exited normally with status 0
2020-10-05 18:58:10,530Z   main - INFO [smart-services] event successfully sent to kafka: com.stitchdata.extractionJobFinished [1] at offset None
2020-10-05 18:58:10,531Z   main - INFO No tunnel subprocess to tear down
2020-10-05 18:58:10,531Z   main - INFO Exit status is: Tap failed with code 1 and error message: "'NoneType' object has no attribute 'split'". Target succeeded.`

**Comment by kizerian** [comment]
Did you find a solution to this error? I'm trying to set up Stitch-GitLab integration myself and I keep having the same problem.

**Comment by 27Bslash6** [comment]
Same issue.

It appears to attempt to proceed if both 'projects' and groups are non-zero, but this is not my requirement.

**Comment by lcolumelli** [comment]
Hey there I am trying to setup the Stitchdata for Gitlab integration too and I still get the same error. Is the integration still working for some of you ?

**Comment by Nicoowr** [comment]
Same here...

**Comment by Nicoowr** [comment]
In my case, this happened when I didn't specify groups. If I fill both repo & groups fields, the extraction works.

**Comment by matt-filion** [comment]
It would be nice if projects was optional. In specifying a group I am already defining the boundaries for the projects I want included.

**Comment by Nicoowr** [comment]
Yes but it seems like the repo is not maintained anymore
